server:
  port: 8080
logging:
  config: classpath:logback.xml
  level:
    org:
      hibernate:
        SQL: DEBEG

        spring:
          datasource:
            url: jdbc:mysql://127:0:0:1:8080/?user=root/lookbook?serverTimezone=UTC&characterEncoding=UTF-8
            username: root
            password: 12341234
            driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZWNyZXQiOiJiZS1maXJzdC1wcm9qZWN0LXNlY3JldCJ9.pqAbZY3rm1ca3DoarLPgBWUkVBoJC_B7ckMWcUu7WdI

  access:
    expriation: 1000*60*60
    header: Authorization