server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

datasource:
  username: root
  password: 12341234
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127:0:0:1:8080/be_first_project?useUnicode=true&characterEncoding=UTF-8



jwt:
  secret-key-source: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZWNyZXQiOiJiZS1maXJzdC1wcm9qZWN0LXNlY3JldCJ9.pqAbZY3rm1ca3DoarLPgBWUkVBoJC_B7ckMWcUu7WdI